import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='nav-root'>
          <Link href="./" className='urls'>
            <Image
              src="/logo.png"
              width={20}
              height={20}
              alt="Picture of the author"
            />
          </Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
